[2025-04-07T00:28:22.672+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-07T00:28:22.689+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: running_airbyte.transform_data.meta_ads_campaigns_run manual__2025-04-07T00:28:18.149982+00:00 [queued]>
[2025-04-07T00:28:22.696+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: running_airbyte.transform_data.meta_ads_campaigns_run manual__2025-04-07T00:28:18.149982+00:00 [queued]>
[2025-04-07T00:28:22.696+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 3
[2025-04-07T00:28:22.706+0000] {taskinstance.py:2890} INFO - Executing <Task(DbtRunLocalOperator): transform_data.meta_ads_campaigns_run> on 2025-04-07 00:28:18.149982+00:00
[2025-04-07T00:28:22.718+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=794) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-07T00:28:22.720+0000] {standard_task_runner.py:72} INFO - Started process 796 to run task
[2025-04-07T00:28:22.721+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'running_airbyte', 'transform_data.meta_ads_campaigns_run', 'manual__2025-04-07T00:28:18.149982+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/meta_ads_dag.py', '--cfg-path', '/tmp/tmp6q41inlg']
[2025-04-07T00:28:22.722+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask transform_data.meta_ads_campaigns_run
[2025-04-07T00:28:22.768+0000] {task_command.py:467} INFO - Running <TaskInstance: running_airbyte.transform_data.meta_ads_campaigns_run manual__2025-04-07T00:28:18.149982+00:00 [running]> on host ffa99f2ae5fe
[2025-04-07T00:28:22.835+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='running_airbyte' AIRFLOW_CTX_TASK_ID='transform_data.meta_ads_campaigns_run' AIRFLOW_CTX_EXECUTION_DATE='2025-04-07T00:28:18.149982+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-07T00:28:18.149982+00:00'
[2025-04-07T00:28:22.837+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-07T00:28:22.837+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-07T00:28:22.837+0000] {logging_mixin.py:190} INFO - Current task name:transform_data.meta_ads_campaigns_run state:running start_date:2025-04-07 00:28:22.689584+00:00
[2025-04-07T00:28:22.838+0000] {logging_mixin.py:190} INFO - Dag name:running_airbyte and current dag run status:running
[2025-04-07T00:28:22.838+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-07T00:28:23.892+0000] {local.py:213} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-04-07T00:28:23.893+0000] {local.py:416} INFO - Cloning project to writable temp directory /tmp/tmpw2po64br from /opt/airflow/dags/dbt/dbt_biera
[2025-04-07T00:28:23.893+0000] {local.py:427} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/running_airbyte__transform_data/target/partial_parse.msgpack
[2025-04-07T00:28:23.900+0000] {config.py:360} INFO - Profile caching is enable.
[2025-04-07T00:28:23.910+0000] {base.py:84} INFO - Retrieving connection 'postgres_conn'
[2025-04-07T00:28:23.911+0000] {config.py:340} INFO - Profile found in cache using profile: /tmp/cosmos/profile/c99bf486c96f06e0233408d45300d7cde96c22a7e21e1f49350115e2a86b810b/profiles.yml.
[2025-04-07T00:28:23.911+0000] {runner.py:60} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'meta_ads_campaigns', '--project-dir', '/tmp/tmpw2po64br', '--profiles-dir', '/tmp/cosmos/profile/c99bf486c96f06e0233408d45300d7cde96c22a7e21e1f49350115e2a86b810b', '--profile', 'default', '--target', 'dev']
 in /tmp/tmpw2po64br
[2025-04-07T00:28:23.979+0000] {logging_mixin.py:190} INFO - 00:28:23  Running with dbt=1.9.3
[2025-04-07T00:28:24.209+0000] {logging_mixin.py:190} INFO - 00:28:24  Registered adapter: postgres=1.9.0
[2025-04-07T00:28:24.918+0000] {logging_mixin.py:190} INFO - 00:28:24  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.dbt_biera.analytics
[2025-04-07T00:28:25.261+0000] {logging_mixin.py:190} INFO - 00:28:25  Found 1 model, 1 source, 434 macros
[2025-04-07T00:28:25.264+0000] {logging_mixin.py:190} INFO - 00:28:25
[2025-04-07T00:28:25.265+0000] {logging_mixin.py:190} INFO - 00:28:25  Concurrency: 1 threads (target='dev')
[2025-04-07T00:28:25.266+0000] {logging_mixin.py:190} INFO - 00:28:25
[2025-04-07T00:28:25.354+0000] {logging_mixin.py:190} INFO - 00:28:25  1 of 1 START sql view model staging.meta_ads_campaigns ......................... [RUN]
[2025-04-07T00:28:25.453+0000] {logging_mixin.py:190} INFO - 00:28:25  1 of 1 OK created sql view model staging.meta_ads_campaigns .................... [CREATE VIEW in 0.10s]
[2025-04-07T00:28:25.463+0000] {logging_mixin.py:190} INFO - 00:28:25
[2025-04-07T00:28:25.463+0000] {logging_mixin.py:190} INFO - 00:28:25  Finished running 1 view model in 0 hours 0 minutes and 0.20 seconds (0.20s).
[2025-04-07T00:28:25.490+0000] {logging_mixin.py:190} INFO - 00:28:25
[2025-04-07T00:28:25.491+0000] {logging_mixin.py:190} INFO - 00:28:25  Completed successfully
[2025-04-07T00:28:25.491+0000] {logging_mixin.py:190} INFO - 00:28:25
[2025-04-07T00:28:25.492+0000] {logging_mixin.py:190} INFO - 00:28:25  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-04-07T00:28:31.358+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/cosmos/operators/local.py:616: UserWarning: The dataset URI postgres://postgres:5432/warehouse.source.meta_ads_campaigns is not AIP-60 compliant: URI format postgres:// must contain database, schema, and table names. In Airflow 3, this will raise an exception.
  datasets = [Dataset(uri) for uri in uris]

[2025-04-07T00:28:31.358+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/cosmos/operators/local.py:616: UserWarning: The dataset URI postgres://postgres:5432/warehouse.staging.meta_ads_campaigns is not AIP-60 compliant: URI format postgres:// must contain database, schema, and table names. In Airflow 3, this will raise an exception.
  datasets = [Dataset(uri) for uri in uris]

[2025-04-07T00:28:31.359+0000] {local.py:465} INFO - Inlets: [Dataset(uri='postgres://postgres:5432/warehouse.source.meta_ads_campaigns', extra=None)]
[2025-04-07T00:28:31.359+0000] {local.py:466} INFO - Outlets: [Dataset(uri='postgres://postgres:5432/warehouse.staging.meta_ads_campaigns', extra=None)]
[2025-04-07T00:28:31.360+0000] {local.py:656} INFO - Assigning inlets/outlets with DatasetAlias
[2025-04-07T00:28:31.409+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-07T00:28:31.409+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=running_airbyte, task_id=transform_data.meta_ads_campaigns_run, run_id=manual__2025-04-07T00:28:18.149982+00:00, execution_date=20250407T002818, start_date=20250407T002822, end_date=20250407T002831
[2025-04-07T00:28:31.417+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/datasets/manager.py:68: UserWarning: The dataset URI postgres://postgres:5432/warehouse.staging.meta_ads_campaigns is not AIP-60 compliant: URI format postgres:// must contain database, schema, and table names. In Airflow 3, this will raise an exception.
  self.notify_dataset_created(dataset=Dataset(uri=dataset_model.uri, extra=dataset_model.extra))

[2025-04-07T00:28:31.417+0000] {taskinstance.py:3054} WARNING - Created a new DatasetModel(uri='postgres://postgres:5432/warehouse.staging.meta_ads_campaigns', extra={}) as it did not exist.
[2025-04-07T00:28:31.422+0000] {taskinstance.py:3064} INFO - Creating event for DatasetModel(uri='postgres://postgres:5432/warehouse.staging.meta_ads_campaigns', extra={}) through aliases "running_airbyte__transform_data__meta_ads_campaigns_run"
[2025-04-07T00:28:31.471+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-07T00:28:31.472+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-07T00:28:31.472+0000] {logging_mixin.py:190} INFO - Dag name:running_airbyte queued_at:2025-04-07 00:28:18.161940+00:00
[2025-04-07T00:28:31.472+0000] {logging_mixin.py:190} INFO - Task hostname:ffa99f2ae5fe operator:DbtRunLocalOperator
[2025-04-07T00:28:31.515+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-07T00:28:31.535+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-07T00:28:31.536+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
