[2025-04-07T12:46:10.714+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-07T12:46:10.732+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: meta_ads_elt_pipeline.dbt_processing.data_transformations.meta_ads_ad_sets_run manual__2025-04-07T12:45:00.112882+00:00 [queued]>
[2025-04-07T12:46:10.741+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: meta_ads_elt_pipeline.dbt_processing.data_transformations.meta_ads_ad_sets_run manual__2025-04-07T12:45:00.112882+00:00 [queued]>
[2025-04-07T12:46:10.741+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 3
[2025-04-07T12:46:10.755+0000] {taskinstance.py:2890} INFO - Executing <Task(DbtRunLocalOperator): dbt_processing.data_transformations.meta_ads_ad_sets_run> on 2025-04-07 12:45:00.112882+00:00
[2025-04-07T12:46:10.771+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=6885) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-07T12:46:10.772+0000] {standard_task_runner.py:72} INFO - Started process 6888 to run task
[2025-04-07T12:46:10.774+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'meta_ads_elt_pipeline', 'dbt_processing.data_transformations.meta_ads_ad_sets_run', 'manual__2025-04-07T12:45:00.112882+00:00', '--job-id', '152', '--raw', '--subdir', 'DAGS_FOLDER/meta_ads_dag.py', '--cfg-path', '/tmp/tmp0lj01ndq']
[2025-04-07T12:46:10.775+0000] {standard_task_runner.py:105} INFO - Job 152: Subtask dbt_processing.data_transformations.meta_ads_ad_sets_run
[2025-04-07T12:46:10.813+0000] {task_command.py:467} INFO - Running <TaskInstance: meta_ads_elt_pipeline.dbt_processing.data_transformations.meta_ads_ad_sets_run manual__2025-04-07T12:45:00.112882+00:00 [running]> on host ffa99f2ae5fe
[2025-04-07T12:46:10.891+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='meta_ads_elt_pipeline' AIRFLOW_CTX_TASK_ID='dbt_processing.data_transformations.meta_ads_ad_sets_run' AIRFLOW_CTX_EXECUTION_DATE='2025-04-07T12:45:00.112882+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-07T12:45:00.112882+00:00'
[2025-04-07T12:46:10.893+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-07T12:46:10.893+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-07T12:46:10.893+0000] {logging_mixin.py:190} INFO - Current task name:dbt_processing.data_transformations.meta_ads_ad_sets_run state:running start_date:2025-04-07 12:46:10.732907+00:00
[2025-04-07T12:46:10.893+0000] {logging_mixin.py:190} INFO - Dag name:meta_ads_elt_pipeline and current dag run status:running
[2025-04-07T12:46:10.894+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-07T12:46:11.924+0000] {local.py:213} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-04-07T12:46:11.924+0000] {local.py:416} INFO - Cloning project to writable temp directory /tmp/tmps5p0kwiz from /opt/airflow/dags/dbt/dbt_biera
[2025-04-07T12:46:11.925+0000] {local.py:427} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/meta_ads_elt_pipeline__dbt_processing__data_transformations/target/partial_parse.msgpack
[2025-04-07T12:46:11.931+0000] {config.py:360} INFO - Profile caching is enable.
[2025-04-07T12:46:11.938+0000] {base.py:84} INFO - Retrieving connection 'postgres_conn'
[2025-04-07T12:46:11.939+0000] {config.py:340} INFO - Profile found in cache using profile: /tmp/cosmos/profile/c99bf486c96f06e0233408d45300d7cde96c22a7e21e1f49350115e2a86b810b/profiles.yml.
[2025-04-07T12:46:11.939+0000] {runner.py:60} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'meta_ads_ad_sets', '--full-refresh', '--project-dir', '/tmp/tmps5p0kwiz', '--profiles-dir', '/tmp/cosmos/profile/c99bf486c96f06e0233408d45300d7cde96c22a7e21e1f49350115e2a86b810b', '--profile', 'default', '--target', 'dev']
 in /tmp/tmps5p0kwiz
[2025-04-07T12:46:12.006+0000] {logging_mixin.py:190} INFO - 12:46:12  Running with dbt=1.9.3
[2025-04-07T12:46:12.238+0000] {logging_mixin.py:190} INFO - 12:46:12  Registered adapter: postgres=1.9.0
[2025-04-07T12:46:12.913+0000] {logging_mixin.py:190} INFO - 12:46:12  Unable to do partial parsing because profile has changed
[2025-04-07T12:46:14.220+0000] {logging_mixin.py:190} INFO - 12:46:14  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.dbt_biera.analytics
[2025-04-07T12:46:14.312+0000] {logging_mixin.py:190} INFO - 12:46:14  Found 2 models, 4 sources, 434 macros
[2025-04-07T12:46:14.314+0000] {logging_mixin.py:190} INFO - 12:46:14
[2025-04-07T12:46:14.315+0000] {logging_mixin.py:190} INFO - 12:46:14  Concurrency: 1 threads (target='dev')
[2025-04-07T12:46:14.316+0000] {logging_mixin.py:190} INFO - 12:46:14
[2025-04-07T12:46:14.418+0000] {logging_mixin.py:190} INFO - 12:46:14  1 of 1 START sql view model staging.meta_ads_ad_sets ........................... [RUN]
[2025-04-07T12:46:14.516+0000] {logging_mixin.py:190} INFO - 12:46:14  1 of 1 OK created sql view model staging.meta_ads_ad_sets ...................... [CREATE VIEW in 0.09s]
[2025-04-07T12:46:14.532+0000] {logging_mixin.py:190} INFO - 12:46:14
[2025-04-07T12:46:14.534+0000] {logging_mixin.py:190} INFO - 12:46:14  Finished running 1 view model in 0 hours 0 minutes and 0.22 seconds (0.22s).
[2025-04-07T12:46:14.582+0000] {logging_mixin.py:190} INFO - 12:46:14
[2025-04-07T12:46:14.583+0000] {logging_mixin.py:190} INFO - 12:46:14  Completed successfully
[2025-04-07T12:46:14.584+0000] {logging_mixin.py:190} INFO - 12:46:14
[2025-04-07T12:46:14.584+0000] {logging_mixin.py:190} INFO - 12:46:14  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-04-07T12:46:15.200+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/cosmos/operators/local.py:616: UserWarning: The dataset URI postgres://postgres:5432/warehouse.source.meta_ads_ad_sets is not AIP-60 compliant: URI format postgres:// must contain database, schema, and table names. In Airflow 3, this will raise an exception.
  datasets = [Dataset(uri) for uri in uris]

[2025-04-07T12:46:15.201+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/cosmos/operators/local.py:616: UserWarning: The dataset URI postgres://postgres:5432/warehouse.staging.meta_ads_ad_sets is not AIP-60 compliant: URI format postgres:// must contain database, schema, and table names. In Airflow 3, this will raise an exception.
  datasets = [Dataset(uri) for uri in uris]

[2025-04-07T12:46:15.201+0000] {local.py:465} INFO - Inlets: [Dataset(uri='postgres://postgres:5432/warehouse.source.meta_ads_ad_sets', extra=None)]
[2025-04-07T12:46:15.202+0000] {local.py:466} INFO - Outlets: [Dataset(uri='postgres://postgres:5432/warehouse.staging.meta_ads_ad_sets', extra=None)]
[2025-04-07T12:46:15.202+0000] {local.py:656} INFO - Assigning inlets/outlets with DatasetAlias
[2025-04-07T12:46:15.249+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-07T12:46:15.249+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=meta_ads_elt_pipeline, task_id=dbt_processing.data_transformations.meta_ads_ad_sets_run, run_id=manual__2025-04-07T12:45:00.112882+00:00, execution_date=20250407T124500, start_date=20250407T124610, end_date=20250407T124615
[2025-04-07T12:46:15.258+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/datasets/manager.py:68: UserWarning: The dataset URI postgres://postgres:5432/warehouse.staging.meta_ads_ad_sets is not AIP-60 compliant: URI format postgres:// must contain database, schema, and table names. In Airflow 3, this will raise an exception.
  self.notify_dataset_created(dataset=Dataset(uri=dataset_model.uri, extra=dataset_model.extra))

[2025-04-07T12:46:15.259+0000] {taskinstance.py:3054} WARNING - Created a new DatasetModel(uri='postgres://postgres:5432/warehouse.staging.meta_ads_ad_sets', extra={}) as it did not exist.
[2025-04-07T12:46:15.265+0000] {taskinstance.py:3064} INFO - Creating event for DatasetModel(uri='postgres://postgres:5432/warehouse.staging.meta_ads_ad_sets', extra={}) through aliases "meta_ads_elt_pipeline__data_transformations__meta_ads_ad_sets_run"
[2025-04-07T12:46:15.316+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-07T12:46:15.316+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-07T12:46:15.316+0000] {logging_mixin.py:190} INFO - Dag name:meta_ads_elt_pipeline queued_at:2025-04-07 12:45:00.123048+00:00
[2025-04-07T12:46:15.316+0000] {logging_mixin.py:190} INFO - Task hostname:ffa99f2ae5fe operator:DbtRunLocalOperator
[2025-04-07T12:46:15.395+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-07T12:46:15.421+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-07T12:46:15.422+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
